name = "NegativeRupert"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["NegativeRupert"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "rupert"
git = "https://github.com/dwrensha/Rupert.lean"
rev = "lean-v4.22.0"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.22.0"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[lean_lib]]
name = "NegativeRupert"

[[lean_exe]]
name = "json-test"
srcDir = "json-test"
root = "Main"